config/routes.rb
Rails.application.routes.draw do
  # Routes for main resources
  resources :stores
  resources :employees
  resources :assignments
  resources :flavors
  resources :store_flavors
  resources :jobs
  resources :shift_jobs
  resources :employees
  resources :shifts
  resources :store_flavors

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  
  # Set the root url
  root :to => 'home#home'  
  # Authentication routes
  resources :sessions
  resources :users
  get 'users/new', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout
  
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  # Callbacks

  before_save :reformat_phone
  before_validation :reformat_ssn
  before_destroy :is_destroyable?
  after_destroy :clean_up_assignment_and_shifts
  after_rollback :terminate_employee

  attr_reader :destroyable
  
  # Relationships
  has_many :assignments
  has_many :stores, through: :assignments
  has_one :user, dependent: :destroy
  has_many :shifts, through: :assignments
  
  accepts_nested_attributes_for :user, reject_if: lambda { |user| user[:email].blank? }, allow_destroy: true
  # Validations
  validates_presence_of :first_name, :last_name, :date_of_birth, :ssn, :role
  validates_date :date_of_birth, on_or_before: lambda { 14.years.ago }, on_or_before_message: "must be at least 14 years old"
  validates_format_of :phone, with: /\A\(?\d{3}\)?[-. ]?\d{3}[-.]?\d{4}\z/, message: "should be 10 digits (area code needed) and delimited with dashes only", allow_blank: true
  validates_format_of :ssn, with: /\A\d{3}[- ]?\d{2}[- ]?\d{4}\z/, message: "should be 9 digits and delimited with dashes only"
  validates_inclusion_of :role, in: %w[admin manager employee], message: "is not an option"
  validates_uniqueness_of :ssn
  
  # Scopes
  scope :younger_than_18, -> { where('date_of_birth > ?', 18.years.ago.to_date) }
  scope :is_18_or_older,  -> { where('date_of_birth <= ?', 18.years.ago.to_date) }
  scope :active,          -> { where(active: true) }
  scope :inactive,        -> { where(active: false) }
  scope :regulars,        -> { where(role: 'employee') }
  scope :managers,        -> { where(role: 'manager') }
  scope :admins,          -> { where(role: 'admin') }
  scope :alphabetical,    -> { order('last_name, first_name') }
  
  # Other methods
  def name
    "#{last_name}, #{first_name}"
  end
  
  def proper_name
    "#{first_name} #{last_name}"
  end
  
  def current_assignment
    curr_assignment = self.assignments.select{|a| a.end_date.nil?}
    # alternative method for finding current assignment is to use scope 'current' in assignments:
    # curr_assignment = self.assignments.current    # will also return an array of current assignments
    return nil if curr_assignment.empty?
    curr_assignment.first   # return as a single object, not an array
  end
  
  def over_18?
    date_of_birth < 18.years.ago.to_date
  end
  
  def age
    (Time.now.to_s(:number).to_i - date_of_birth.to_time.to_s(:number).to_i)/10e9.to_i
  end
  
  # Misc Constants
  ROLES_LIST = [['Employee', 'employee'],['Manager', 'manager'],['Administrator', 'admin']]
  
  
  # Callback code  (NOT DRY!!!)
  # -----------------------------
  private
  def reformat_phone
    phone = self.phone.to_s  # change to string in case input as all numbers 
    phone.gsub!(/[^0-9]/,"") # strip all non-digits
    self.phone = phone       # reset self.phone to new string
  end

  def reformat_ssn
    ssn = self.ssn.to_s      # change to string in case input as all numbers 
    ssn.gsub!(/[^0-9]/,"")   # strip all non-digits
    self.ssn = ssn           # reset self.ssn to new string
  end

  def is_destroyable?
    @destroyable = self.shifts.past.empty?
  end

  def remove_upcoming_shifts
    @future_shifts = self.shifts.upcoming
    @future_shifts.each {|s| s.destroy} unless @future_shifts.empty?
  end

  def clean_up_assignment_and_shifts
    if @destroyable
      remove_upcoming_shifts
      self.current_assignment.delete unless self.current_assignment.nil?
    end
    @destroyable = nil
  end

  def end_current_assignment
    current_assignment = self.current_assignment    
    unless current_assignment.nil?
      current_assignment.update_attribute(:end_date, Date.current)
    end
  end

  def terminate_employee
    if !@destroyable.nil? && @destroyable == false
      remove_upcoming_shifts
      end_current_assignment
    end
    @destroyable = nil
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  load_and_authorize_resource
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  
  def index
    !authorize! :read, @active_employees
    @active_employees = Employee.active.alphabetical.paginate(page: params[:page]).per_page(10)
    @inactive_employees = Employee.inactive.alphabetical.paginate(page: params[:page]).per_page(10)
  end

  def show
    @past_shifts = @employee.shifts.past
    @upcoming_shifts = @employee.shifts.upcoming
    # get the assignment history for this employee
    @assignments = @employee.assignments.chronological.paginate(page: params[:page]).per_page(5)
    # get upcoming shifts for this employee (later)  
  end

  def new
    @employee = Employee.new
  end

  def edit
    @mail = @employee.user.email
  end

  def create
    @employee = Employee.new(employee_params)
    
    if @employee.save
      redirect_to employee_path(@employee), notice: "Successfully created #{@employee.proper_name}."
    else
      render action: 'new'
    end
  end

  def update
    if @employee.update(employee_params)
      redirect_to employee_path(@employee), notice: "Successfully updated #{@employee.proper_name}."
    else
      render action: 'edit'
    end
  end

  def destroy
    @employee.destroy
    redirect_to employees_path, notice: "Successfully removed #{@employee.proper_name} from the AMC system."
  end

  private
  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :ssn, :date_of_birth, :role, :phone, :active,user_attributes: [:email, :password, :password_confirmation, :employee_id, :_destroy])
  end

end

app/views/employees/_assignment_history.html.erb
<h3>Assignment History</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Store</th>
      <th>Dates</th>
      <th class="centered">Pay Level</th>
    </tr>
  </thead>
  <tbody>
    <% @assignments.each do |assignment| %>
      <tr>
        <td><%= link_to assignment.store.name, store_path(assignment.store) %></td>
        <td>
          <%= assignment.start_date.strftime("%m/%d/%y") %>
          <% if assignment.end_date.nil? %>
            &nbsp;&nbsp;&nbsp;
            <%= link_to(edit_assignment_path(assignment), class: 'button tiny radius warning') do %>
              &nbsp;End&nbsp;
            <% end %>
          <% else %>
            &nbsp;-&nbsp;<%= assignment.end_date.strftime("%m/%d/%y") %>
          <% end %>
        </td>
        <td class="centered"><%= assignment.pay_level %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @assignments, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>

app/views/employees/_current_employees.html.erb
<% if @active_employees.empty? %>
  <p><em>There are no current employees at this time.</em></p>
<% else %>
  <h3>Current Employees</h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Phone</th>
        <th>Currently Assigned</th>
        <th>Role</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% @active_employees.each do |employee| %>
        <tr>
          <td><%= link_to employee.name, employee_path(employee) %></td>
          <td><%= number_to_phone employee.phone unless employee.phone.nil?  %></td>
          <td><%= link_to employee.current_assignment.store.name, store_path(employee.current_assignment.store) unless employee.current_assignment.nil? %></td>
          <td><%= employee.role.capitalize %></td>
          <td>
            <%= link_to(edit_employee_path(employee), class: 'button tiny radius warning') do %>
              &nbsp;Edit&nbsp;
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @active_employees, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>

<% end %>

app/views/employees/_employee_details.html.erb
<h3>Employee Details</h3>
<p>
  <h4>
    Name: <%= @employee.name %>
  </h4>
</p>

<p>
  <b>SSN:</b> <%= @employee.ssn %>
</p>

<p>
  <b>Date of Birth:</b> <%= @employee.date_of_birth.strftime("%m/%d/%y") %>
</p>

<p>
  <b>Phone:</b> <%= number_to_phone @employee.phone unless @employee.phone.nil? %>
</p>

<p>
  <b>Role:</b> <%= @employee.role.capitalize %>
</p>

<p>
  <b>Active:</b> <%= @employee.active ? "Yes" : "No" %>
</p>

app/views/employees/_employee_fields.html.erb
<%= f.input :first_name, input_html: {class: "avg"} %>
    <%= f.input :last_name, input_html: {class: "avg"} %>
    <%= f.input :ssn, input_html: {class: "avg"} %>
    <%= f.input :date_of_birth, as: :date, start_year: Date.today.year - 13,
                              end_year: Date.today.year - 90,
                              order: [:month, :day, :year], include_blank: true, input_html: {class: "avg"} %>

    <%= f.input :phone, input_html: {class: "avg"} %>
    <%= f.input :role, collection: Employee::ROLES_LIST, include_blank: true, input_html: {class: "avg"} %>
    <%= f.input :active %>

   

app/views/employees/_form.html.erb
<%= simple_nested_form_for @employee, :html => { :class => 'form-horizontal' } do |employee_form| %>
    <div class="row">
      <div class="span7">
        <fieldset>
          <legend><%= controller.action_name.capitalize %> Employee</legend>
          <%= render :partial => "employee_fields", :locals => { :f => employee_form } %>
        </fieldset>
      </div>
    <% if controller.action_name == "new" %>

    <div class="span5">
      <legend>Create an account for this Employee</legend>
        <div id="employee_user">
          <%= employee_form.simple_fields_for :user do |user_form| %>
            <%= render :partial => "user_fields", :locals => { :f => user_form } %>
          <% end %> 
            <p>
            <br /><%= employee_form.link_to_add("Add User", :user, :class => 'button tiny') %>
          </p>
        </div> 
      </div>
    </div>
    <% end %>
    <% if controller.action_name == "edit" %>
     <div class="span5">
      <legend>Edit Employee Account</legend>
        <div id="employee_user">
          <%= employee_form.simple_fields_for :user do |user_form| %>
            <%= render :partial => "user_fields", :locals => { :f => user_form } %>
          <% end %> 


        </div> 
      </div>
    </div>
    <% end %>
    <div class="form-actions">
      <%= employee_form.submit nil, :class => 'button radius' %>
      <%= link_to 'Cancel', employees_path, :class => 'button secondary' %>
    </div>
  <% end %>

app/views/employees/_inactive_employees.html.erb
<% unless @inactive_employees.empty? %>
  <div class="panel callout radius">
    <h3>Inactive Employees</h3>
    <ul>
      <% @inactive_employees.each do |employee| %>
        <li><%= link_to employee.name, employee_path(employee) %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/employees/_store_details.html.erb
<p>
  <h4>
    Name: <%= @store.name %>
  </h4>
</p>

<p>
  <b>Address:</b><br>
  <%= @store.street %><br />
  <%= @store.city %>, <%= @store.state %> <%= @store.zip %>
</p>

<p>
  <b>Phone:</b><br>
  <%= number_to_phone @store.phone %>
</p>

<p>
  <b>Active:</b> 
  <%= @store.active ? "Yes" : "No" %>
</p>

app/views/employees/_upcoming_shifts.html.erb
<h3>Upcoming Shifts</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th class="centered">Start Time</th>
    </tr>
  </thead>
  <tbody>
    <% @upcoming_shifts.each do |shift| %>
      <tr>
        <td><%= link_to shift.date, shift_path(shift) %></td>
        <td class="centered"><%= shift.start_time.strftime('%r') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employees/_user_fields.html.erb
  <%= f.input :employee_id, :collection => Employee.active.alphabetical, :include_blank => true, input_html: {class: "avg"} %>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email, value: @mail %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>

app/views/employees/_user_fields_edit.html.erb
<%= e.simple_form_for :user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :employee_id, :collection => Employee.active.alphabetical, :include_blank => true, input_html: {class: "avg"} %>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit (@user.new_record? ? "Sign up" : "Update") %></p>
<% end %>

app/views/employees/edit.html.erb
<%= render :partial => "partials/display_form" %>

app/views/employees/index.html.erb
<%= render partial: "partials/index_structure", locals: {model_name: "employee", 
                                                         primary: "current_employees", 
                                                         secondary: nil,
                                                         sidebar: "inactive_employees"} %>

app/views/employees/new.html.erb
<%= render :partial => "partials/display_form" %>

app/views/employees/show.html.erb
<div class="row">
  <div class="small-7 columns">
    <%= render partial: "employee_details" %>
  </div>
  <div class="small-5 columns">
    <%= render partial: "assignment_history" unless @assignments.empty?%>
  </div>
  <div class="small-5 columns">
    <%= render partial: "upcoming_shifts" unless @upcoming_shifts.empty?%>
  </div>
</div>

<!-- Add buttons to list all, edit project or destroy object -->
<%= render partial: "partials/object_options", locals: {model_name: "employee", object: @employee}  %>