config/routes.rb
Rails.application.routes.draw do
  # Routes for main resources
  resources :stores
  resources :employees
  resources :assignments
  resources :flavors
  resources :store_flavors
  resources :jobs
  resources :shift_jobs
  resources :employees
  resources :shifts
  resources :store_flavors

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  
  # Set the root url
  root :to => 'home#home'  
  # Authentication routes
  resources :sessions
  resources :users
  get 'users/new', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout
  
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  # get modules to help with some functionality
  include CreameryHelpers::Validations

  # Callbacks
  before_create :end_previous_assignment
  before_update :remove_future_shifts_from_terminated_assignment
  before_destroy :is_destroyable?
  after_rollback :terminate_assignment
  
  # Relationships
  belongs_to :employee
  belongs_to :store
  has_many :shifts
  
  # Validations
  validates_numericality_of :pay_level, only_integer: true, greater_than: 0, less_than: 7
  validates_date :start_date, on_or_before: lambda { Date.current }, on_or_before_message: "cannot be in the future"
  validates_date :end_date, after: :start_date, on_or_before: lambda { Date.current }, allow_blank: true
  validate :employee_is_active_in_system, on: :create
  validate :store_is_active_in_system, on: :create
  validates_presence_of :employee_id, on: :update
  validates_presence_of :store_id, on: :update
  
  # Scopes
  scope :current,       -> { where(end_date: nil) }
  scope :past,          -> { where.not(end_date: nil) }
  scope :by_store,      -> { joins(:store).order('name') }
  scope :by_employee,   -> { joins(:employee).order('last_name, first_name') }
  scope :chronological, -> { order('start_date DESC, end_date DESC') }
  scope :for_store,     ->(store_id) { where("store_id = ?", store_id) }
  scope :for_employee,  ->(employee_id) { where("employee_id = ?", employee_id) }
  scope :for_pay_level, ->(pay_level) { where("pay_level = ?", pay_level) }
  scope :for_role,      ->(role) { joins(:employee).where("role = ?", role) }

  # Private methods for callbacks and custom validations
  private  
  
  def end_previous_assignment
    current_assignment = Employee.find(self.employee_id).current_assignment
    if current_assignment.nil?
      return true 
    else
      terminate_all_future_shifts
      current_assignment.update_attribute(:end_date, self.start_date.to_date)
    end
  end
  
  def employee_is_active_in_system
    is_active_in_system(:employee)
  end

  def store_is_active_in_system
    is_active_in_system(:store)
  end

  def remove_future_shifts_from_terminated_assignment
    terminate_all_future_shifts unless self.end_date.nil?
  end

  def terminate_all_future_shifts
    @future_shifts = self.shifts.upcoming
    @future_shifts.each {|s| s.destroy}
  end

  def is_destroyable?
    @destroyable = self.shifts.past.empty?
  end
  
  def terminate_assignment
    terminate_all_future_shifts if !@destroyable.nil? && @destroyable == false
    self.update_attribute(:end_date, Date.current)if !@destroyable.nil? && @destroyable == false
    @destroyable = nil
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  load_and_authorize_resource

  before_action :set_assignment, only: [:edit, :update, :destroy]
  # before_action :set_assignment, only: [:show, :edit, :update, :destroy]

  def index
    @current_assignments = Assignment.current.by_store.by_employee.chronological.paginate(page: params[:page]).per_page(15)
    @past_assignments = Assignment.past.by_employee.by_store.paginate(page: params[:page]).per_page(15)  
  end

  # def show
  #   # get the shift history for this assignment (later; empty now)
  #   @shifts = Array.new
  # end

  def new
    @assignment = Assignment.new

    # if params[:from].nil?
    #   if params[:id].nil?
    #     @assignment = Assignment.new
    #   else
    #     @assignment = Assignment.find(params[:id])
    #   end
    # else
    #   @assignment = Assignment.new
    #   if params[:from] == "store" 
    #     @assignment.store_id = params[:id]
    #   else
    #     @assignment.employee_id = params[:id]
    #   end
    # end
  end

  def edit
  end

  def create
    @assignment = Assignment.new(assignment_params)
    
    if @assignment.save
      redirect_to assignments_path, notice: "#{@assignment.employee.proper_name} is assigned to #{@assignment.store.name}."
      # redirect_to assignment_path(@assignment), notice: "#{@assignment.employee.proper_name} is assigned to #{@assignment.store.name}."
    else
      render action: 'new'
    end
  end

  def update
    if @assignment.update(assignment_params)
      redirect_to assignments_path, notice: "#{@assignment.employee.proper_name}'s assignment to #{@assignment.store.name} is updated."
    else
      render action: 'edit'
    end
  end

  def destroy
    @assignment.destroy
    redirect_to assignments_path, notice: "Successfully removed #{@assignment.employee.proper_name} from #{@assignment.store.name}."
  end

  private
  def set_assignment
    @assignment = Assignment.find(params[:id])
  end

  def assignment_params
    params.require(:assignment).permit(:employee_id, :store_id, :start_date, :end_date, :pay_level)
  end

end

app/views/assignments/_assignment_details.html.erb
<h3>Assignment Details</h3>
<br />
<p>
  <b>Store</b>: <%= link_to @assignment.store.name, store_path(@assignment.store) %>
</p>

<p>
  <b>Employee</b>: <%= link_to @assignment.employee.name, employee_path(@assignment.employee) %>
</p>

<p>
  <b>Start date</b>: <%= @assignment.start_date.strftime("%m/%d/%y") %>
</p>

<p>
  <b>End date</b>: 
  <% if @assignment.end_date.nil? %>
    &nbsp;&nbsp;<em>TBD</em>
  <% else %>
    <%= @assignment.end_date.strftime("%m/%d/%y") %>
  <% end %>
</p>

<p>
  <b>Pay level</b>: <%= @assignment.pay_level %>
</p>

app/views/assignments/_assignment_list.html.erb
<% if assignments.empty? %>
  <p><em>There are no <%= state %> assignments at this time.</em></p>
<% else %>
  <h3><%= state.capitalize %> Assignments</h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Store</th>
        <th>Employee</th>
        <th class="centered">Pay</th>
        <th>Start Date</th>
        <% if state == 'past' %>
          <th>End Date</th>
        <% end %>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% assignments.each do |assignment| %>
        <tr>
          <td><%= link_to assignment.store.name, store_path(assignment.store) %></td>
          <td><%= link_to assignment.employee.name, employee_path(assignment.employee) %></td>
          <td class="centered"><%= assignment.pay_level %></td>
          <td><%= assignment.start_date.strftime("%m/%d/%y") %></td>
          <% if state == 'past' %>
            <td><%= assignment.end_date.strftime("%m/%d/%y") %></td>
          <% end %>
          <td>
            <%= link_to(edit_assignment_path(assignment), class: 'button tiny radius warning') do %>
              &nbsp;Edit&nbsp;
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate assignments, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>  
<% end %>
<p>&nbsp;</p>

app/views/assignments/_current_assignments.html.erb
<% unless @current_assignments.empty? %>
  <%= render partial: "assignment_list", locals: {assignments: @current_assignments, state: 'current'} %>
<% end %>

app/views/assignments/_form.html.erb
<%= simple_form_for @assignment, html: { class: 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Assignment</legend>

    <%= f.input :store_id, :collection => Store.active.alphabetical, :include_blank => true, input_html: {class: "avg"} %>
    <%= f.input :employee_id, :collection => Employee.active.alphabetical, :include_blank => true, input_html: {class: "avg"} %>
     <%= f.input :start_date, as: :date_picker, :label => 'Start Date',
                input_html: {data: {date_options: {
                        defaultDate: Date.today.strftime('%D')
                }}} %>
    <%# Only show the end_date on 'edit', not 'new' %>
    <% if controller.action_name == "edit" %>
       <%= f.input :end_date, as: :date_picker, :label => 'End Date',
                input_html: {data: {date_options: {
                        defaultDate: Date.today.strftime('%D')
                }}} %>
    <% end %>
    
    <%= f.input :pay_level, :collection => 1..6, :include_blank => true, input_html: {class: "avg"} %>

    <div class="form-actions">
      <%= f.submit nil, :class => 'button radius' %>
      <%= link_to 'Cancel', assignments_path, :class => 'button alert radius' %>
    </div>
  </fieldset>
<% end %>

app/views/assignments/_past_assignments.html.erb
<% unless @past_assignments.empty? %>
  <%= render partial: "assignment_list", locals: {assignments: @past_assignments, state: 'past'} %>
<% end %>

app/views/assignments/_shift_history.html.erb
<!-- <p>Forthcoming...</p> -->

app/views/assignments/edit.html.erb
<%= render :partial => "partials/display_form" %>

app/views/assignments/index.html.erb
<%= render partial: "partials/index_structure_2", locals: {model_name: "assignment", 
                                                         primary: "current_assignments", 
                                                         secondary: "past_assignments",
                                                         sidebar: nil} %>

app/views/assignments/new.html.erb
<%= render :partial => "partials/display_form" %>

app/views/assignments/show.html.erb
<div class="row">
  <div class="small-7 columns">
    <%= render partial: "assignment_details" %>
  </div>
  <div class="small-5 columns">
    <%= render partial: "shift_history" unless @shifts.empty?%>
  </div>
</div>

<!-- Add buttons to list all, edit project or destroy object -->
<%= render partial: "partials/object_options", locals: {model_name: "assignment", object: @assignment}  %>