config/routes.rb
Rails.application.routes.draw do
  # Routes for main resources
  resources :stores
  resources :employees
  resources :assignments
  resources :flavors
  resources :store_flavors
  resources :jobs
  resources :shift_jobs
  resources :employees
  resources :shifts
  resources :store_flavors

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  
  # Set the root url
  root :to => 'home#home'  
  # Authentication routes
  resources :sessions
  resources :users
  get 'users/new', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout
  
end

app/views/partials/_address_info.html.erb
  <%= store.street %><br />
  <%= store.city %>, <%= store.state %> <%= store.zip %>

app/views/partials/_display_form.html.erb
<div class="row">
  <div class="small-8 columns">
    <%= render :partial => "form" %>
  </div>
</div>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box <%= flash[:notice] ? "success" : "warning" %> radius">
    <a href="#" class="close">&times;</a>
    <%= msg %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<footer>

	<%= link_to 'Home', home_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'About the Creamery', about_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
	<%= link_to 'Contact Us', contact_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
	<%= link_to 'Privacy Policy', privacy_path %>
	<br /><br />
	
	<div id="copy">
		Webmaster: <%= mail_to("congrenw@andrew.cmu.edu", "Andrew Wang", encode: "javascript") %> 
		&nbsp;&nbsp;&copy 2016
	</div>

</footer>

app/views/partials/_index_structure.html.erb
<div class="row">
  <div class="small-8 columns">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
    
  </div>
  <div class="small-4 columns">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>

<!-- Add a button for new instances of object -->
<%= link_to(eval("new_#{model_name}_path"), class: "button radius") do %>
  <!-- <i class="fa fa-plus"></i> -->
  &nbsp;Add a New <%= model_name.capitalize %>
<% end %>

app/views/partials/_index_structure_2.html.erb
<div class="row">
  <div class="small-9 columns">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
    
  </div>
  <div class="small-3 columns">
    <!-- Add a button for new instances of object -->
    <%= link_to(eval("new_#{model_name}_path"), class: "button radius") do %>
      <!-- <i class="fa fa-plus"></i> -->
      &nbsp;Add a New <%= model_name.capitalize %>
    <% end %>
  </div>
</div>

app/views/partials/_nav.html.erb
<div class="contain-to-grid">
  <nav class="top-bar" data-topbar role="navigation"> 
    <section class="top-bar-section">
      <ul class="left">
        <!-- link to home -->
        <li><%= link_to "Home", home_path %></li>

        <li class="has-dropdown">
          <%= link_to "Other" %>
          <ul class="dropdown">
            <li><%= link_to "Flavor List", flavors_path %></li>
            <li><%= link_to "Add a Flavor", new_flavor_path %></li>
            <li><%= link_to "Job List", jobs_path %></li>
            <li><%= link_to "Add a Job", new_job_path %></li>
            <li><%= link_to "Shift/Job Connections", shift_jobs_path %></li>
            <li><%= link_to "Add a Shift/Job", new_shift_job_path %></li>
            <li><%= link_to "Store/Flavor Connections", store_flavors_path %></li>
            <li><%= link_to "Add a Store/Flavor", new_store_flavor_path %></li>
          </ul>
        </li>

        <li class="has-dropdown">
          <%= link_to "Shifts", shifts_path %>
          <ul class="dropdown">
            <li><%= link_to "Shift List", shifts_path %></li>
            <li><%= link_to "Add a Shift", new_shift_path %></li>
          </ul>
        </li>

        <!-- options for stores -->
        <li class="has-dropdown">
          <%= link_to "Stores", stores_path %>
          <ul class="dropdown">
            <li><%= link_to "Store List", stores_path %></li>
            <li><%= link_to "Add a Store", new_store_path %></li>
          </ul>
        </li>

        <!-- options for employees -->
        <li class="has-dropdown">
          <%= link_to "Employees", employees_path %>
          <ul class="dropdown">
            <li><%= link_to "Employee List", employees_path %></li>
            <li><%= link_to "Add an Employee", new_employee_path %></li>
          </ul>
        </li>

        <!-- options for assignments -->
        <li class="has-dropdown">
          <%= link_to "Assignments", assignments_path %>
          <ul class="dropdown">
            <li><%= link_to "Assignments List", assignments_path %></li>
            <li><%= link_to "Create New Assignment", new_assignment_path %></li>
          </ul>
        </li>
      </ul>
 <!-- options for stores -->
        
    </section>
  </nav>
</div>

app/views/partials/_object_options.html.erb
  <% opt = "#{object.respond_to?(:name) ? object.name : model_name.capitalize }" %>

  <div class="form-actions">
    <%= link_to(eval("#{model_name.pluralize}_path"), class: 'button radius') do %>
      &nbsp;Display All <%= model_name.pluralize.capitalize %>
    <% end %>
    &nbsp;&nbsp;
    
    <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'button radius') do %>
        &nbsp;<%= "Edit #{opt}" %>
    <% end %>
    &nbsp;&nbsp;
    
    <%= link_to(eval("#{model_name}_path(object)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete #{opt}"}, class: 'button radius alert') do %>
        &nbsp;<%= "Delete #{opt}" %>
    <% end %>
  </div>

app/views/partials/_show_structure.html.erb
<div class="row">
  <div class="small-7 columns">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
    
  </div>
  <div class="small-5 columns">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>

<!-- Add buttons to list all, edit project or destroy object -->
<%= render partial: "partials/object_options", locals: {model_name: "#{model_name}", object: @object}  %>