config/routes.rb
Rails.application.routes.draw do
  # Routes for main resources
  resources :stores
  resources :employees
  resources :assignments
  resources :flavors
  resources :store_flavors
  resources :jobs
  resources :shift_jobs
  resources :employees
  resources :shifts
  resources :store_flavors

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  
  # Set the root url
  root :to => 'home#home'  
  # Authentication routes
  resources :sessions
  resources :users
  get 'users/new', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout
  
end

app/models/shift.rb
class Shift < ActiveRecord::Base
  # Relationships
  has_many :shift_jobs
  has_many :jobs, through: :shift_jobs
  belongs_to :assignment
  has_one :employee, through: :assignment
  has_one :store, through: :assignment

  # Validations
  validates_date :date, on_or_after: lambda { :assignment_starts }, on_or_before_message: "must be on or after the start of the assignment"
  validates_time :start_time
  validates_time :end_time, after: :start_time, allow_blank: true
  validate :assignment_must_be_current

  # Scopes
  scope :chronological, -> { order(:date, :start_time) }
  scope :by_store, -> { joins(:assignment, :store).order('stores.name') }
  scope :by_employee, -> { joins(:assignment, :employee).order('employees.last_name, employees.first_name') }
  scope :past, -> { where('date < ?', Date.current) }
  scope :upcoming, -> { where('date >= ?', Date.current) }
  scope :for_employee, ->(employee_id) { joins(:assignment, :employee).where("assignments.employee_id = ?", employee_id) }
  scope :for_store, ->(store_id) { joins(:assignment, :store).where("assignments.store_id = ?", store_id) }
  scope :for_next_days, ->(x) { where('date BETWEEN ? AND ?', Date.today, x.days.from_now.to_date) }
  scope :for_past_days, ->(x) { where('date BETWEEN ? AND ?', x.days.ago.to_date, 1.day.ago.to_date) }
  scope :completed, -> { joins(:shift_jobs).group(:shift_id) }
  scope :incomplete, -> { joins("LEFT JOIN shift_jobs ON shifts.id = shift_jobs.shift_id").where('shift_jobs.job_id IS NULL') }
  # alternative ways of finding 'incomplete' scope:
  # scope :incomplete, -> { where('id NOT IN (?)', Shift.completed.map(&:id)) }
  # a class method to also find incomplete shifts using array operations...
  def self.not_completed
    all_shifts = Shift.all
    completed_shifts = Shift.completed
    incompleted_shifts = all_shifts - completed_shifts
  end

  # Other methods
  def completed?
    self.shift_jobs.count > 0
  end

  def start_now
    self.update_attribute(:start_time, Time.current)
  end

  def end_now
    self.update_attribute(:end_time, Time.current)
  end

  def duration
    # returns the duration of the shift in units of hours (fractional)
    # since creamery not opened past midnight, don't have to
    # worry about crossing into next day, so just ...
    (self.end_time - self.start_time)/3600.0
  end
  
  # callback to set default end_time (on create only)
  before_create :set_shift_end_time
  
  private
  def assignment_starts
    @assignment_starts = self.assignment.start_date.to_date
  end
  
  def assignment_must_be_current
    unless self.assignment.nil? || self.assignment.end_date.nil?
      errors.add(:assignment_id, "is not a current assignment at the creamery")
    end
  end
  
  def set_shift_end_time
    self.end_time = self.start_time + (3*60*60)
  end

end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  load_and_authorize_resource
  before_action :set_shift, only: [:show, :edit, :update, :destroy]
  
  def index
    @shifts = Shift.all.paginate(page: params[:page]).per_page(10)  
  end

  def show
    @worked_jobs = @shift.jobs.paginate(page: params[:page]).per_page(4)
  end

  def new
    @shift = Shift.new
  end

  def edit
  end

  def create
    @shift = Shift.new(shift_params)
    
    if @shift.save
      redirect_to shift_path(@shift), notice: "Successfully created #{@shift}."
    else
      render action: 'new'
    end
  end

  def update
    if @shift.update(shift_params)
      redirect_to shift_path(@shift), notice: "Successfully updated #{@shift}."
    else
      render action: 'edit'
    end
  end

  def destroy
    @shift.destroy
    redirect_to shifts_path, notice: "Successfully removed #{@shift} from the AMC system."
  end

  private
  def set_shift
    @shift = Shift.find(params[:id])
  end

  def shift_params
    params.require(:shift).permit(:assignment_id, :date, :start_time, :end_time, :notes)
  end

end

app/views/shifts/_form.html.erb
<%= simple_form_for(@shift) do |f| %>
  <% if @shift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      <ul>
      <% @shift.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :assignment_id %><br>
    <%= f.number_field :assignment_id %>
  </div>
  <div class="field">
    <%= f.input :date, as: :date_picker, :label => 'Date',
                input_html: {data: {date_options: {
                        defaultDate: Date.today.strftime('%D')
                }}} %> 
  <div class="field">
    <%= f.input :start_time, as: :time_picker, :label => 'Start Time'%>
  </div>
  <div class="field">
    <%= f.input :end_time, as: :time_picker, :label => 'End Time'%>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shifts/_shift_details.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Assignment:</strong>
  <%= @shift.assignment_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @shift.date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @shift.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @shift.end_time %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @shift.notes %>
</p>

app/views/shifts/_worked_jobs.html.erb
<h3>Jobs Worked</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Job</th>
      <th class="centered">Description</th>
    </tr>
  </thead>
  <tbody>
    <% @worked_jobs.each do |job| %>
      <tr>
        <td><%= link_to job.name, job_path(job) %></td>
        <td class="centered"><%= job.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @worked_jobs, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>

app/views/shifts/edit.html.erb
<h1>Editing shift</h1>

<%= render 'form' %>

<%= link_to 'Show', @shift %> |
<%= link_to 'Back', shifts_path %>

app/views/shifts/index.html.erb
<h1>Listing shifts</h1>

<table>
  <thead>
    <tr>
      <th>Assignment</th>
      <th>Date</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Notes</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @shifts.each do |shift| %>
      <tr>
        <td><%= shift.assignment_id %></td>
        <td><%= shift.date %></td>
        <td><%= shift.start_time %></td>
        <td><%= shift.end_time %></td>
        <td><%= shift.notes %></td>
        <td><%= link_to 'Show', shift %></td>
        <td><%= link_to 'Edit', edit_shift_path(shift) %></td>
        <td><%= link_to 'Destroy', shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shift', new_shift_path %>

app/views/shifts/new.html.erb
<h1>New shift</h1>

<%= render 'form' %>

<%= link_to 'Back', shifts_path %>

app/views/shifts/show.html.erb
<div class="row">
  <div class="small-7 columns">
    <%= render partial: "shift_details" %>
  </div>

 <div class="small-5 columns">
    <%= render partial: "worked_jobs" unless @worked_jobs.empty?%>
  </div>
</div>
<%= link_to 'Edit', edit_shift_path(@shift) %> |
<%= link_to 'Back', shifts_path %>